COC:

  判定_大成功:
    - - "……大成功。保持专注即可，{$t玩家}。"
      - 1
    - - "大成功。很好。"
      - 1

  判定_成功_极难:
    - - "极难成功。技巧与运气都在你这边。"
      - 1

  判定_成功_困难:
    - - "困难成功。节奏感稳定。"
      - 1

  判定_成功_普通:
    - - "成功。继续。"
      - 1

  判定_失败:
    - - "……失败。不要急，整理一下呼吸。"
      - 1

  判定_大失败:
    - - "大失败。状态不佳，现在先停下。"
      - 1

  检定:
    - - "{$t原因 ? ''由于'' + $t原因 + ''，''}{$t玩家}的检定结果：{$t结果文本}"
      - 1

  检定_单项结果文本:
    - - "{$t检定表达式文本}={$tD100}/{$t判定值}{$t检定计算过程} {$t判定结果}"
      - 1

  制卡:
    - - |-
        {$t玩家}的人物作成完成：
        {$t制卡结果文本}
      - 1

  对抗检定:
    - - |-
        对抗检定：
        {$t玩家A} → {$t玩家A判定结果}
        {$t玩家B} → {$t玩家B判定结果}
        {% $tWinFlag == -1 ? $t玩家A + '胜出。',
           $tWinFlag == +1 ? $t玩家B + '胜出。',
           $tWinFlag == 0 ? '平手。需要自行判断场景。'
        %}
      - 1

  结束:
    - - "……我先回练习室。需要我的时候再叫我。"
      - 1
